# Config file for automatic testing at travis-ci.org

branches:
  # Exclude some branches (whose names start with WIP) from travis
  except:
    - /^(WIP).*$/

language: python

python:
  - "3.5"
  - "3.6"

install:
  - sudo apt-get update
  - pip install -r requirements.txt
  - pip install -r test_requirements.txt
  - pip install .

before_script:
  # Start x virtual framebuffer for gui
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  # give xvfb some time to start
  - sleep 3

script:
  - coverage run --omit=pyinduct/tests/*,setup.py setup.py test

after_success:
  - codecov
